### ISSUE TITLE
Missing source code for tests/binary/bomb

### ISSUE THREAD

**Issue by joebb97** [season-lab/memsight#2]
Hi there! We are working on updating this project to python3 and the latest version of `angr` (whose most recent version only supports python3) for 
our Advanced Systems course (EECS 582) at the University of Michigan. We've been tasked with improving `angr`'s existing symbolic memory model, and our research showed that memsight is one of the better solutions. Our fork is here -> https://github.com/anrddh/memsight

We're trying to get your existing tests passing again, and we've made pretty good progress thus far, but some are giving us some issues (we've also broken CI builds on our end too lol). The `tests/binary/bomb` one is a good example, but its source code seems to be missing from the repository.

We welcome any insight, questions, concerns, or contributions you might be able to offer to our project. Thanks!

**Comment by ercoppa** [comment]
HI @joebb97!

 I am happy that you are porting MemSight to a newer version of angr, l'll keep an eye on your fork :)

> The tests/binary/bomb one is a good example, but its source code seems to be missing from the repository.

I don't have the source code since it is a "crackme" used in one CMU course (https://www.cs.cmu.edu/~213/assignments.html) and the source code is not provided to students. If you search for "CMU bomb" online, you can find many writeups (however: there are slightly different versions of it, keep this in mind). angr is also using the CMU bomb as one of [their examples](https://github.com/angr/angr-doc/tree/master/examples/cmu_binary_bomb).

**Comment by joebb97** [comment]
Ah, that makes sense. Thanks for the info! Hope you're all doing well and staying safe in these trying times.
